<?php


namespace App\Services\Repositories\Manage\Providers;

use App\Services\Repositories\Manage\Interfaces\IManage;
use App\Services\Repositories\Manage\Interfaces\IManageLog;
use App\Services\Repositories\Manage\Interfaces\IManageModule;
use App\Services\Repositories\Manage\Interfaces\IManageRole;
use App\Services\Repositories\Manage\ManageLogRepo;
use App\Services\Repositories\Manage\ManageModuleRepo;
use App\Services\Repositories\Manage\ManageRepo;
use App\Services\Repositories\Manage\ManageRoleRepo;
use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

class RepositoryServiceProvider extends ServiceProvider
{
    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function register()
    {
        $this->app->bind(IManage::class, ManageRepo::class);//管理员
        $this->app->bind(IManageModule::class, ManageModuleRepo::class);//管理员权限模块
        $this->app->bind(IManageLog::class, ManageLogRepo::class);//管理员日志
        $this->app->bind(IManageRole::class, ManageRoleRepo::class);//管理员角色
    }
}
