<?php


namespace App\Services\Repositories\UCenter\Providers;

use App\Services\Repositories\UCenter\Interfaces\IMember;
use App\Services\Repositories\UCenter\Interfaces\IMemberGroup;
use App\Services\Repositories\UCenter\MemberGroupRepo;
use App\Services\Repositories\UCenter\MemberRepo;
use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

class RepositoryServiceProvider extends ServiceProvider
{
    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function register()
    {
        $this->app->bind(IMember::class, MemberRepo::class);//用户管理
        $this->app->bind(IMemberGroup::class, MemberGroupRepo::class);//用户组管理
    }
}
